require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TracksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Track. As you add validations to Track, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:track_attributes)
  }

  let(:track_attributes) {
    {track_track: valid_attributes[:track_points],
     track_starts: valid_attributes[:starts],
     track_ends: valid_attributes[:ends]}
  }

  let(:valid_track) {
    FactoryGirl.create :track
  }

  let(:invalid_attributes) {
    FactoryGirl.attributes_for :track_attributes, name: ''
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TracksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tracks as @tracks" do
      valid_track
      get :index, {}, valid_session
      expect(assigns(:tracks)).to eq([valid_track])
    end
  end

  describe "GET show" do
    it "assigns the requested track as @track" do
      get :show, {:id => valid_track.to_param}, valid_session
      expect(assigns(:track)).to eq(valid_track)
    end
  end

  describe "GET new" do
    it "assigns a new track as @track" do
      get :new, {}, valid_session
      expect(assigns(:track)).to be_a_new(Track)
    end
  end

  describe "GET edit" do
    it "assigns the requested track as @track" do
      get :edit, {:id => valid_track.to_param}, valid_session
      expect(assigns(:track)).to eq(valid_track)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Track" do
        expect {
          post :create, {:track => valid_attributes}.merge(track_attributes), valid_session
        }.to change(Track, :count).by(1)
      end

      it "assigns a newly created track as @track" do
        post :create, {:track => valid_attributes}.merge(track_attributes), valid_session
        expect(assigns(:track)).to be_a(Track)
        expect(assigns(:track)).to be_persisted
      end

      it "redirects to the track map" do
        post :create, {:track => valid_attributes}.merge(track_attributes), valid_session
        expect(response).to redirect_to(root_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved track as @track" do
        post :create, {:track => invalid_attributes}.merge(track_attributes), valid_session
        expect(assigns(:track)).to be_a_new(Track)
      end

      it "re-renders the 'new' template" do
        post :create, {:track => invalid_attributes}.merge(track_attributes), valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        FactoryGirl.attributes_for :new_track_attributes
      }

      it "updates the requested track" do
        put :update, {:id => valid_track.to_param, :track => new_attributes}.merge(track_attributes), valid_session
        valid_track.reload
        expect(assigns(:track).name).to eq(valid_track.name)
      end

      it "assigns the requested track as @track" do
        put :update, {:id => valid_track.to_param, :track => valid_attributes}.merge(track_attributes), valid_session
        expect(assigns(:track)).to eq(valid_track)
      end

      it "redirects to the track" do
        put :update, {:id => valid_track.to_param, :track => valid_attributes}.merge(track_attributes), valid_session
        expect(response).to redirect_to(valid_track)
      end
    end

    describe "with invalid params" do
      it "assigns the track as @track" do
        put :update, {:id => valid_track.to_param, :track => invalid_attributes}.merge(track_attributes), valid_session
        expect(assigns(:track)).to eq(valid_track)
      end

      it "re-renders the 'edit' template" do
        put :update, {:id => valid_track.to_param, :track => invalid_attributes}.merge(track_attributes), valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested track" do
      valid_track
      expect {
        delete :destroy, {:id => valid_track.to_param}, valid_session
      }.to change(Track, :count).by(-1)
    end

    it "redirects to the tracks list" do
      delete :destroy, {:id => valid_track.to_param}, valid_session
      expect(response).to redirect_to(root_url)
    end
  end

end
